### ISSUE TITLE
Index page loads slow

### ISSUE THREAD

**Issue by txqzzz** [HellooYing/MCQ_Blog#2]
When I first start the index page, it loads for much time that i can barely wait..Maybe you can just improve the performance of images loading.

**Comment by satouriko** [comment]
Could anybody kindly tell me where can I visit this blog?

**Comment by txqzzz** [comment]
Maybe [this](https://www.hellooying.xyz/#) will help

**Comment by txqzzz** [comment]
Maybe [this](http://www.hellooying.xyz/#) will help.

**Comment by satouriko** [comment]
cool

**Comment by HellooYing** [comment]
喵喵喵

**Comment by HellooYing** [comment]
现在去弄一下CDN，但愿能快一丢丢

**Comment by HellooYing** [comment]
希望不会被小程序队友看见
阿弥陀佛 我没在摸鱼
