### ISSUE TITLE
Add a readme.md and license to enable us to contribute.

### ISSUE THREAD

**Issue by Anduin2017** [HellooYing/MCQ_Blog#4]
This was a project so nice but did not include a readme.md file and license file. Please add it and tell more about how to run and how to contribute.

**Comment by HellooYing** [comment]
贡献是什么鬼 帮我写我的博客吗hhhhhh

**Comment by Anduin2017** [comment]
显然不是。这里贡献指的是，比如你的代码有错，我们就可以开修。这是开源最大的价值。

**Comment by Anduin2017** [comment]
你的博客写这么好，应该在readme文件里多讲讲如何运行这个项目，以及如何部署，维护。这样我们也可以从你的工作中受益。

**Comment by Anduin2017** [comment]
如果你接受了建议，并进行了修改，就可以close这个issue了

**Comment by HellooYing** [comment]
soga  还有这种操作
